[theme]
primaryColor = "#006400"       # UdeA green color for primary elements
backgroundColor = "#FFFFFF"    # White background
secondaryBackgroundColor = "#F0F2F6"   # Lighter background for the sidebar and other components
textColor = "#000000"          # Black text color for better readability
font = "sans serif"            # A clean, professional font

# To hide the Streamlit menu and footer
[server]
headless = true

[client]
hideStreamlitBanner = true      # Hide the "Made with Streamlit" banner

[ui]
hideToolbar = true              # Hide the Streamlit menu (hamburger)
