[theme]
primaryColor = "#006400"       # UdeA green color for primary elements
backgroundColor = "#FFFFFF"    # White background
secondaryBackgroundColor = "#F0F2F6"   # Lighter background for the sidebar and other components
textColor = "#000000"          # Black text color for better readability
font = "sans serif"            # A clean, professional font

# To hide the Streamlit menu and footer
[server]
headless = true

[client]
hideStreamlitBanner = true      # Hide the "Made with Streamlit" banner

[ui]
hideToolbar = true              # Hide the Streamlit menu (hamburger)

# Page settings
[page]
title = "UdeA Medical Case Chatbot"     # A catchy and descriptive title
favicon = "UdeA+simplificado-01.png"    # Use your UdeA logo as favicon (make sure it's a small size like 32x32px)

